#!/usr/bin/env bash
#
# update_dashboard.sh — regenerates data/dashboard.md from data/leads.json
#
# Contract: reads data/leads.json (schema documented in skills/outreach-draft/SKILL.md)
# Writes:   data/dashboard.md (fully overwritten each run)
#
# Invoked by:
#   - skills/outreach-draft/SKILL.md at the end of each run
#   - Manually:  bash scripts/update_dashboard.sh
#
# Requires: jq

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LEADS="${ROOT}/data/leads.json"
DASH="${ROOT}/data/dashboard.md"

if [[ ! -f "$LEADS" ]]; then
  echo "update_dashboard: leads.json not found at $LEADS" >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "update_dashboard: jq is required but not installed" >&2
  exit 1
fi

NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

# ---- Counts per pipeline stage ------------------------------------------------
SCOUTED=$(jq '[.leads[]] | length' "$LEADS")
QUALIFIED=$(jq '[.leads[] | select(.status == "qualified" or .status == "qualified-low" or .status == "outreach-drafted")] | length' "$LEADS")
DRAFTED=$(jq '[.leads[] | select(.status == "outreach-drafted")] | length' "$LEADS")
APPROVED=$(jq '[.leads[] | select(.outreach_status == "approved" or .outreach_status == "sent")] | length' "$LEADS")
SKIPPED=$(jq '[.leads[] | select(.status == "skipped")] | length' "$LEADS")

# ---- Score distribution -------------------------------------------------------
# Supports both legacy `.score` and current `.marketing_score` field names.
BAND_HIGH=$(jq '[.leads[] | (.marketing_score // .score) as $s | select($s != null and $s <= 3)] | length' "$LEADS")
BAND_GOOD=$(jq '[.leads[] | (.marketing_score // .score) as $s | select($s != null and $s >= 4 and $s <= 6)] | length' "$LEADS")
BAND_SOFT=$(jq '[.leads[] | (.marketing_score // .score) as $s | select($s != null and $s >= 7 and $s <= 8)] | length' "$LEADS")
BAND_SKIP=$(jq '[.leads[] | (.marketing_score // .score) as $s | select($s != null and $s >= 9)] | length' "$LEADS")

# ---- Recent leads rows (latest 10, newest first) -----------------------------
RECENT_ROWS=$(jq -r '
  .leads
  | sort_by(.drafted_at // .enriched_at // .found_at // .scouted_at // "")
  | reverse
  | .[0:10]
  | to_entries
  | map(
      "| \(.key + 1) "
      + "| \(.value.product_name // "—") "
      + "| \(.value.founder_name // "—") "
      + "| \(.value.marketing_score // .value.score // "—") "
      + "| \(.value.source // "—") "
      + "| \((.value.top_gaps // [])[0] // "—") "
      + "| \(.value.status // "—") |"
    )
  | .[]
' "$LEADS")

if [[ -z "$RECENT_ROWS" ]]; then
  RECENT_ROWS="| — | — | — | — | — | — | — |"
fi

# ---- Top gaps (rolling, most frequent first) ---------------------------------
TOP_GAPS=$(jq -r '
  [.leads[].top_gaps // [] | .[]]
  | group_by(.)
  | map({gap: .[0], count: length})
  | sort_by(-.count)
  | .[0:5]
  | map("- **\(.count)×** \(.gap)")
  | .[]
' "$LEADS")

if [[ -z "$TOP_GAPS" ]]; then
  TOP_GAPS="_No data yet. Run the pipeline to populate._"
fi

# ---- Last run timestamp from leads.json metadata -----------------------------
LAST_RUN=$(jq -r '.metadata.last_updated // "—"' "$LEADS")

# ---- Write dashboard ---------------------------------------------------------
cat > "$DASH" <<EOF
# GrowthClaw Dashboard

> **Status:** ready · **Last pipeline run:** ${LAST_RUN} · **Dashboard regenerated:** ${NOW}
>
> Auto-generated by \`scripts/update_dashboard.sh\`. Do not edit by hand — changes are overwritten on every run.

---

## Pipeline Status

| Stage              | Count |
|--------------------|-------|
| 🔎 Scouted         | ${SCOUTED} |
| 🧪 Qualified       | ${QUALIFIED} |
| 🎯 Outreach Drafted| ${DRAFTED} |
| ✉️  Approved        | ${APPROVED} |
| 🛑 Skipped         | ${SKIPPED} |

## Score Distribution

| Band | Meaning | Count |
|------|---------|-------|
| 1–3  | 🔥 High priority (severe gaps) | ${BAND_HIGH} |
| 4–6  | 🎯 Good fit (moderate gaps)    | ${BAND_GOOD} |
| 7–8  | 🫱 Soft pitch (light gaps)     | ${BAND_SOFT} |
| 9–10 | ⏭️  Skipped (already polished)  | ${BAND_SKIP} |

## Recent Leads (latest 10)

| # | Product | Founder | Score | Source | Hero Gap | Status |
|---|---------|---------|-------|--------|----------|--------|
${RECENT_ROWS}

## Top Gaps Found (rolling)

${TOP_GAPS}

## Pending Outreach (fallback queue)

_Messages land here when Slack is unreachable. The outreach-draft skill writes the same Block Kit content here as Markdown so nothing is lost._

---

### Legend

- **Score** — 1 (worst marketing) to 10 (already strong). Score ≥ 9 is auto-skipped.
- **Hero Gap** — the single marketing gap the outreach message references. Chosen from the lead's \`top_gaps[0]\`.
- **Status** — \`scouted\` → \`qualified\` → \`outreach-drafted\` → \`approved\` → \`sent\` → \`replied\`. \`skipped\` is terminal.
EOF

echo "update_dashboard: wrote $DASH (scouted=${SCOUTED}, qualified=${QUALIFIED}, drafted=${DRAFTED})"
